name: Code Quality and Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: maximum_path_sum_python
          channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          conda install pylint
      - name: Code Review Scoring
        run: |
          conda activate maximum_path_sum_python
          find . -name '*.py' -exec pylint {} \;
        shell: bash -l {0}
      - name: List Python files
        run: |
          find . -name '*.py'
        shell: /usr/bin/bash -l {0}
      - name: Run PyLint
        run: |
          FILES=$(find . -name '*.py')
          if [ -z "$FILES" ]; then
            echo "No Python files to lint."
          else
            pylint $FILES --fail-under=8.0
          fi
        shell: /usr/bin/bash -l {0}
      - name: Run Tests and Generate Coverage Report
        run: |
          pip install coverage pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      - name: Run Ruff for fast Python linting
        uses: chartboost/ruff-action@v1
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

